# ================================
# BASE DE DATOS - H2 (en memoria)
# ================================
spring.datasource.url=jdbc:h2:mem:control_escolar
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ================================
# CONSOLA H2 (para ver tus tablas en el navegador)
# ================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ================================
# JPA / HIBERNATE
# ================================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ================================
# JWT
# ================================
jwt.secret=clave-super-secreta-control-escolar-2024-debe-ser-larga
jwt.expiration=86400000

# ================================
# SERVIDOR
# ================================
server.port=8080
spring.application.name=apiescolar